gantt
    tickInterval 1day
    title Open Accounts with: an IRA company, a Bank, & some Centralized Exchanges (CEXs)
    dateFormat YYYY-MM-DD
    section IRA Company
        Open Traditional Self Directed IRA    :a1, 2023-01-01, 1d
        Create Checkbook LLC                  :2023-01-02, 1d
    section Bank or Credit Union
        Open Business Checking Acct           :2023-01-03, 1d
    section Centralized Exchange 1
        Open Institutional Account            :2023-01-04, 1d
    section Centralized Exchange 2
        Open Institutional Account            :2023-01-04, 1d
    section Centralized Exchange 3
        Open Institutional Account            :2023-01-04, 1d


%%{
  init: {
    'theme': 'default',
    'themeVariables': {
      'fontFamily': 'Inter'
    }
  }
}%%

